### ISSUE TITLE
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', limitador/src/limit.rs:131:29

### ISSUE THREAD

**Issue by andwang130** [Kuadrant/limitador#94]
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', limitador/src/limit.rs:131:29

**Comment by alexsnaps** [comment]
This is due to a `condition` of a `Limit` that isn't properly formatted. Currently the format is pretty strict: `variable == value` where even the space matter. I have some work on-going that catches those when the limit is loaded, unlike now where it fails _when the limit is evaluated_. I'm also working on making the parsing more robust... 
This should be addressed by the next release
